version: '1.1'
languages:
  java:
    packages:
      zombie.worldMap:
        WorldMapSettings.MiniMap:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            Isometric:
              name: Isometric
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            ShowSymbols:
              name: ShowSymbols
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            StartVisible:
              name: StartVisible
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            TerrainImage:
              name: TerrainImage
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            Zoom:
              name: Zoom
              modifiers:
              - public
              type:
                basic: DoubleConfigOption
                full: zombie.config.DoubleConfigOption
            this$0:
              name: this$0
              modifiers:
              - package
              type:
                basic: WorldMapSettings
                full: zombie.worldMap.WorldMapSettings
          constructors:
          - modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: WorldMapSettings
                full: zombie.worldMap.WorldMapSettings
