version: '1.1'
languages:
  java:
    packages:
      zombie.audio:
        MusicThreatConfig:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            m_statusById:
              name: m_statusById
              modifiers:
              - private
              type:
                basic: HashMap
                full: java.util.HashMap<java.lang.String, zombie.audio.MusicThreatConfig$Status>
            m_statusList:
              name: m_statusList
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.audio.MusicThreatConfig$Status>
          staticFields:
            instance:
              name: instance
              modifiers:
              - private
              - static
              type:
                basic: MusicThreatConfig
                full: zombie.audio.MusicThreatConfig
          constructors:
          - modifiers:
            - public
          methods:
          - name: getStatusCount
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getStatusIdByIndex
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getStatusIntensity
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: float
                full: float
          - name: getStatusIntensityByIndex
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: float
                full: float
          - name: getStatusIntensityOverride
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: float
                full: float
          - name: initStatuses
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: KahluaTableImpl
                full: se.krka.kahlua.j2se.KahluaTableImpl
            return:
              type:
                basic: void
                full: void
          - name: isStatusIntensityOverridden
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: setStatusIntensityOverride
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          staticMethods:
          - name: getInstance
            modifiers:
            - public
            - static
            return:
              type:
                basic: MusicThreatConfig
                full: zombie.audio.MusicThreatConfig
