version: '1.1'
languages:
  java:
    packages:
      zombie.audio:
        MusicThreatConfig.Status:
          extends: java.lang.Object
          modifiers:
          - package
          - final
          fields:
            m_id:
              name: m_id
              modifiers:
              - package
              type:
                basic: String
                full: java.lang.String
            m_intensity:
              name: m_intensity
              modifiers:
              - package
              type:
                basic: float
                full: float
            m_intensityOverride:
              name: m_intensityOverride
              modifiers:
              - package
              type:
                basic: float
                full: float
          constructors:
          - modifiers:
            - private
