version: '1.1'
languages:
  java:
    packages:
      zombie.audio:
        MusicIntensityConfig.Event:
          extends: java.lang.Object
          modifiers:
          - package
          - final
          fields:
            m_bMultiple:
              name: m_bMultiple
              modifiers:
              - package
              type:
                basic: boolean
                full: boolean
            m_duration:
              name: m_duration
              modifiers:
              - package
              type:
                basic: long
                full: long
            m_id:
              name: m_id
              modifiers:
              - package
              type:
                basic: String
                full: java.lang.String
            m_intensity:
              name: m_intensity
              modifiers:
              - package
              type:
                basic: float
                full: float
          constructors:
          - modifiers:
            - private
