version: '1.1'
languages:
  java:
    packages:
      zombie.core:
        PerformanceSettings:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          staticFields:
            AnimationSkip:
              name: AnimationSkip
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            BaseStaticAnimFramerate:
              name: BaseStaticAnimFramerate
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            FBORenderChunk:
              name: FBORenderChunk
              modifiers:
              - public
              - static
              type:
                basic: boolean
                full: boolean
            FogQuality:
              name: FogQuality
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            InterpolateAnims:
              name: InterpolateAnims
              modifiers:
              - public
              - static
              type:
                basic: boolean
                full: boolean
            LightingFPS:
              name: LightingFPS
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            LightingThread:
              name: LightingThread
              modifiers:
              - public
              - static
              type:
                basic: boolean
                full: boolean
            ManualFrameSkips:
              name: ManualFrameSkips
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            ModelLighting:
              name: ModelLighting
              modifiers:
              - public
              - static
              type:
                basic: boolean
                full: boolean
            NewRoofHiding:
              name: NewRoofHiding
              modifiers:
              - public
              - static
              type:
                basic: boolean
                full: boolean
            PuddlesQuality:
              name: PuddlesQuality
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            UseFBOs:
              name: UseFBOs
              modifiers:
              - public
              - static
              type:
                basic: boolean
                full: boolean
            ViewConeOpacity:
              name: ViewConeOpacity
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            WaterQuality:
              name: WaterQuality
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            ZombieAnimationSpeedFalloffCount:
              name: ZombieAnimationSpeedFalloffCount
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            ZombieBonusFullspeedFalloff:
              name: ZombieBonusFullspeedFalloff
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            auto3DZombies:
              name: auto3DZombies
              modifiers:
              - public
              - static
              type:
                basic: boolean
                full: boolean
            instance:
              name: instance
              modifiers:
              - public
              - static
              type:
                basic: PerformanceSettings
                full: zombie.core.PerformanceSettings
            numberZombiesBlended:
              name: numberZombiesBlended
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            s_lockFPS:
              name: s_lockFPS
              modifiers:
              - private
              - static
              type:
                basic: int
                full: int
            s_uncappedFPS:
              name: s_uncappedFPS
              modifiers:
              - private
              - static
              type:
                basic: boolean
                full: boolean
          constructors:
          - modifiers:
            - public
          methods:
          - name: getFogQuality
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getFramerate
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getLightingFPS
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getLightingQuality
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getNewRoofHiding
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getPuddlesQuality
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getUIRenderFPS
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getViewConeOpacity
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getWaterQuality
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: isFramerateUncapped
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: setFogQuality
            modifiers:
            - public
            parameters:
            - name: fogQuality
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setFramerate
            modifiers:
            - public
            parameters:
            - name: framerate
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setFramerateUncapped
            modifiers:
            - public
            parameters:
            - name: val
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setLightingFPS
            modifiers:
            - public
            parameters:
            - name: fps
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setLightingQuality
            modifiers:
            - public
            parameters:
            - name: lighting
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setNewRoofHiding
            modifiers:
            - public
            parameters:
            - name: enabled
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setPuddlesQuality
            modifiers:
            - public
            parameters:
            - name: puddles
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setViewConeOpacity
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setWaterQuality
            modifiers:
            - public
            parameters:
            - name: water
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          staticMethods:
          - name: getLockFPS
            modifiers:
            - public
            - static
            return:
              type:
                basic: int
                full: int
          - name: setLockFPS
            modifiers:
            - public
            - static
            parameters:
            - name: lockFPS
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
