version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.contextmenuconfig:
        ContextMenuConfigScript.EntryScript:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            allowDistance:
              name: allowDistance
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            customFunction:
              name: customFunction
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            customSubmenu:
              name: customSubmenu
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            extraParam:
              name: extraParam
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            icon:
              name: icon
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            menu:
              name: menu
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            openWindow:
              name: openWindow
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            time:
              name: time
              modifiers:
              - private
              type:
                basic: int
                full: int
            timedAction:
              name: timedAction
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
          constructors:
          - modifiers:
            - public
          methods:
          - name: getAllowDistance
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getCustomFunction
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getCustomSubmenu
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getExtraParam
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getIcon
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getMenu
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getOpenWindow
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getTime
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getTimedAction
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
