version: '1.1'
languages:
  java:
    packages:
      java.util.concurrent:
        ConcurrentHashMap.ValuesView:
          extends: java.util.concurrent.ConcurrentHashMap$CollectionView<K, V, V>
          modifiers:
          - package
          - final
          staticFields:
            serialVersionUID:
              name: serialVersionUID
              modifiers:
              - private
              - static
              type:
                basic: long
                full: long
          constructors:
          - modifiers:
            - package
            parameters:
            - name: arg0
              type:
                basic: ConcurrentHashMap
                full: java.util.concurrent.ConcurrentHashMap<K, V>
          methods:
          - name: add
            modifiers:
            - public
            - final
            parameters:
            - name: arg0
              type:
                basic: V
                full: V
            return:
              type:
                basic: boolean
                full: boolean
          - name: addAll
            modifiers:
            - public
            - final
            parameters:
            - name: arg0
              type:
                basic: Collection
                full: java.util.Collection<? extends V>
            return:
              type:
                basic: boolean
                full: boolean
          - name: contains
            modifiers:
            - public
            - final
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: boolean
                full: boolean
          - name: forEach
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Consumer
                full: java.util.function.Consumer<? super V>
            return:
              type:
                basic: void
                full: void
          - name: iterator
            modifiers:
            - public
            - final
            return:
              type:
                basic: Iterator
                full: java.util.Iterator<V>
          - name: remove
            modifiers:
            - public
            - final
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: boolean
                full: boolean
          - name: removeAll
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Collection
                full: java.util.Collection<?>
            return:
              type:
                basic: boolean
                full: boolean
          - name: removeIf
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Predicate
                full: java.util.function.Predicate<? super V>
            return:
              type:
                basic: boolean
                full: boolean
          - name: spliterator
            modifiers:
            - public
            return:
              type:
                basic: Spliterator
                full: java.util.Spliterator<V>
