version: '1.1'
languages:
  java:
    packages:
      zombie.entity.components.spriteconfig:
        SpriteConfigManager.FaceInfo:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            face:
              name: face
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            height:
              name: height
              modifiers:
              - private
              type:
                basic: int
                full: int
            isMasterSet:
              name: isMasterSet
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            isMultiSquare:
              name: isMultiSquare
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            masterPosX:
              name: masterPosX
              modifiers:
              - private
              type:
                basic: int
                full: int
            masterPosY:
              name: masterPosY
              modifiers:
              - private
              type:
                basic: int
                full: int
            masterPosZ:
              name: masterPosZ
              modifiers:
              - private
              type:
                basic: int
                full: int
            sprites:
              name: sprites
              modifiers:
              - private
              type:
                basic: HashMap
                full: java.util.HashMap<java.lang.String, zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo>
            tileInfos:
              name: tileInfos
              modifiers:
              - private
              type:
                basic: SpriteConfigManager.TileInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo[][][]
            width:
              name: width
              modifiers:
              - private
              type:
                basic: int
                full: int
            zLayers:
              name: zLayers
              modifiers:
              - private
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: int
                full: int
            - name: arg3
              type:
                basic: int
                full: int
          methods:
          - name: CreateEmpty
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: boolean
                full: boolean
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: int
                full: int
            - name: arg3
              type:
                basic: int
                full: int
            return:
              type:
                basic: SpriteConfigManager.TileInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo
          - name: CreateTile
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: int
                full: int
            - name: arg3
              type:
                basic: int
                full: int
            - name: arg4
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: SpriteConfigManager.TileInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo
          - name: ensureTileInfos
            modifiers:
            - protected
            return:
              type:
                basic: void
                full: void
          - name: getFaceName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getHeight
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMainSpriteName
            modifiers:
            - protected
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getMasterTileInfo
            modifiers:
            - public
            return:
              type:
                basic: SpriteConfigManager.TileInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo
          - name: getMasterX
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMasterY
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMasterZ
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getTileInfo
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: int
                full: int
            return:
              type:
                basic: SpriteConfigManager.TileInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo
          - name: getTileInfoForSprite
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: SpriteConfigManager.TileInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo
          - name: getWidth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getzLayers
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: isMasterSet
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isMultiSquare
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: verifyObject
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: int
                full: int
            - name: arg3
              type:
                basic: IsoObject
                full: zombie.iso.IsoObject
            return:
              type:
                basic: boolean
                full: boolean
