version: '1.1'
languages:
  java:
    packages:
      zombie.entity.components.spriteconfig:
        SpriteOverlayConfig:
          extends: zombie.entity.Component
          modifiers:
          - public
          fields:
            appliedStyle:
              name: appliedStyle
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            configScript:
              name: configScript
              modifiers:
              - private
              type:
                basic: SpriteOverlayConfigScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript
          constructors:
          - modifiers:
            - private
          methods:
          - name: clearStyle
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: getAvailableStyles
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
          - name: hasStyle
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: isValid
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: load
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: arg1
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: loadSyncData
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: onEntityEvent
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: EntityEvent
                full: zombie.entity.events.EntityEvent
            return:
              type:
                basic: void
                full: void
          - name: onReceivePacket
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: arg1
              type:
                basic: EntityPacketType
                full: zombie.entity.network.EntityPacketType
            - name: arg2
              type:
                basic: UdpConnection
                full: zombie.core.raknet.UdpConnection
            return:
              type:
                basic: boolean
                full: boolean
          - name: readFromScript
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ComponentScript
                full: zombie.scripting.entity.ComponentScript
            return:
              type:
                basic: void
                full: void
          - name: reset
            modifiers:
            - protected
            return:
              type:
                basic: void
                full: void
          - name: save
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: saveSyncData
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: setStyle
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: updateStyle
            modifiers:
            - private
            return:
              type:
                basic: void
                full: void
