version: '1.1'
languages:
  java:
    packages:
      zombie.iso.weather:
        ClimateValues:
          extends: java.lang.Object
          modifiers:
          - public
          notes: TurboTuTone.
          fields:
            airFrontAirmass:
              name: airFrontAirmass
              modifiers:
              - private
              type:
                basic: float
                full: float
            airMassNoiseFrequencyMod:
              name: airMassNoiseFrequencyMod
              modifiers:
              - private
              type:
                basic: double
                full: double
            airMassTemperature:
              name: airMassTemperature
              modifiers:
              - private
              type:
                basic: float
                full: float
            ambient:
              name: ambient
              modifiers:
              - private
              type:
                basic: float
                full: float
            baseTemperature:
              name: baseTemperature
              modifiers:
              - private
              type:
                basic: float
                full: float
            cacheDay:
              name: cacheDay
              modifiers:
              - private
              type:
                basic: int
                full: int
            cacheMonth:
              name: cacheMonth
              modifiers:
              - private
              type:
                basic: int
                full: int
            cacheWorldAgeHours:
              name: cacheWorldAgeHours
              modifiers:
              - private
              type:
                basic: double
                full: double
            cacheYear:
              name: cacheYear
              modifiers:
              - private
              type:
                basic: int
                full: int
            clim:
              name: clim
              modifiers:
              - private
              type:
                basic: ClimateManager
                full: zombie.iso.weather.ClimateManager
            cloudIntensity:
              name: cloudIntensity
              modifiers:
              - private
              type:
                basic: float
                full: float
            cloudyT:
              name: cloudyT
              modifiers:
              - private
              type:
                basic: float
                full: float
            dawn:
              name: dawn
              modifiers:
              - private
              type:
                basic: float
                full: float
            dayDoFog:
              name: dayDoFog
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            dayFogDuration:
              name: dayFogDuration
              modifiers:
              - private
              type:
                basic: float
                full: float
            dayFogStrength:
              name: dayFogStrength
              modifiers:
              - private
              type:
                basic: float
                full: float
            dayLightLagged:
              name: dayLightLagged
              modifiers:
              - private
              type:
                basic: float
                full: float
            dayLightStrength:
              name: dayLightStrength
              modifiers:
              - private
              type:
                basic: float
                full: float
            dayLightStrengthBase:
              name: dayLightStrengthBase
              modifiers:
              - private
              type:
                basic: float
                full: float
            dayMeanTemperature:
              name: dayMeanTemperature
              modifiers:
              - private
              type:
                basic: float
                full: float
            desaturation:
              name: desaturation
              modifiers:
              - private
              type:
                basic: float
                full: float
            dusk:
              name: dusk
              modifiers:
              - private
              type:
                basic: float
                full: float
            gt:
              name: gt
              modifiers:
              - private
              type:
                basic: GameTime
                full: zombie.GameTime
            humidity:
              name: humidity
              modifiers:
              - private
              type:
                basic: float
                full: float
            lerpNight:
              name: lerpNight
              modifiers:
              - private
              type:
                basic: float
                full: float
            nightLagged:
              name: nightLagged
              modifiers:
              - private
              type:
                basic: float
                full: float
            nightStrength:
              name: nightStrength
              modifiers:
              - private
              type:
                basic: float
                full: float
            noiseAirmass:
              name: noiseAirmass
              modifiers:
              - private
              type:
                basic: float
                full: float
            noon:
              name: noon
              modifiers:
              - private
              type:
                basic: float
                full: float
            seededRandom:
              name: seededRandom
              modifiers:
              - private
              type:
                basic: Random
                full: java.util.Random
            simplexOffsetA:
              name: simplexOffsetA
              modifiers:
              - private
              type:
                basic: double
                full: double
            simplexOffsetB:
              name: simplexOffsetB
              modifiers:
              - private
              type:
                basic: double
                full: double
            simplexOffsetC:
              name: simplexOffsetC
              modifiers:
              - private
              type:
                basic: double
                full: double
            simplexOffsetD:
              name: simplexOffsetD
              modifiers:
              - private
              type:
                basic: double
                full: double
            temperature:
              name: temperature
              modifiers:
              - private
              type:
                basic: float
                full: float
            temperatureIsSnow:
              name: temperatureIsSnow
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            testCurrentDay:
              name: testCurrentDay
              modifiers:
              - private
              type:
                basic: ClimateManager.DayInfo
                full: zombie.iso.weather.ClimateManager$DayInfo
            testNextDay:
              name: testNextDay
              modifiers:
              - private
              type:
                basic: ClimateManager.DayInfo
                full: zombie.iso.weather.ClimateManager$DayInfo
            time:
              name: time
              modifiers:
              - private
              type:
                basic: float
                full: float
            windAngleDegrees:
              name: windAngleDegrees
              modifiers:
              - private
              type:
                basic: float
                full: float
            windAngleIntensity:
              name: windAngleIntensity
              modifiers:
              - private
              type:
                basic: float
                full: float
            windIntensity:
              name: windIntensity
              modifiers:
              - private
              type:
                basic: float
                full: float
          constructors:
          - modifiers:
            - public
            parameters:
            - name: clim
              type:
                basic: ClimateManager
                full: zombie.iso.weather.ClimateManager
          methods:
          - name: CopyValues
            modifiers:
            - public
            parameters:
            - name: copy
              type:
                basic: ClimateValues
                full: zombie.iso.weather.ClimateValues
            return:
              type:
                basic: void
                full: void
          - name: getAirFrontAirmass
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getAirMassNoiseFrequencyMod
            modifiers:
            - public
            return:
              type:
                basic: double
                full: double
          - name: getAirMassTemperature
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getAmbient
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getBaseTemperature
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getCacheDay
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getCacheMonth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getCacheWorldAgeHours
            modifiers:
            - public
            return:
              type:
                basic: double
                full: double
          - name: getCacheYear
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getCloudIntensity
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getCloudyT
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getCopy
            modifiers:
            - public
            return:
              type:
                basic: ClimateValues
                full: zombie.iso.weather.ClimateValues
          - name: getDawn
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDayFogDuration
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDayFogStrength
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDayLightLagged
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDayLightStrength
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDayLightStrengthBase
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDayMeanTemperature
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDesaturation
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDusk
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getHumidity
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getLerpNight
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getNightLagged
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getNightStrength
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getNoiseAirmass
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getNoon
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getTemperature
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getTime
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getWindAngleDegrees
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getWindAngleIntensity
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getWindIntensity
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: isDayDoFog
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isTemperatureIsSnow
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: pollDate
            modifiers:
            - public
            parameters:
            - name: year
              type:
                basic: int
                full: int
            - name: month
              type:
                basic: int
                full: int
            - name: dayOfMonth
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: pollDate
            modifiers:
            - public
            parameters:
            - name: year
              type:
                basic: int
                full: int
            - name: month
              type:
                basic: int
                full: int
            - name: dayOfMonth
              type:
                basic: int
                full: int
            - name: hourOfDay
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: pollDate
            modifiers:
            - public
            parameters:
            - name: year
              type:
                basic: int
                full: int
            - name: month
              type:
                basic: int
                full: int
            - name: dayOfMonth
              type:
                basic: int
                full: int
            - name: hourOfDay
              type:
                basic: int
                full: int
            - name: minute
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: pollDate
            modifiers:
            - public
            parameters:
            - name: calendar
              type:
                basic: GregorianCalendar
                full: java.util.GregorianCalendar
            return:
              type:
                basic: void
                full: void
          - name: print
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: updateValues
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: double
                full: double
            - name: arg1
              type:
                basic: float
                full: float
            - name: arg2
              type:
                basic: ClimateManager.DayInfo
                full: zombie.iso.weather.ClimateManager$DayInfo
            - name: arg3
              type:
                basic: ClimateManager.DayInfo
                full: zombie.iso.weather.ClimateManager$DayInfo
            return:
              type:
                basic: void
                full: void
