version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteConfigScript.ZLayer:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            rows:
              name: rows
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$XRow>
          constructors:
          - modifiers:
            - public
          methods:
          - name: getHeight
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getRow
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: SpriteConfigScript.XRow
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$XRow
          - name: getVersion
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: IVersionHash
                full: zombie.world.scripts.IVersionHash
            return:
              type:
                basic: void
                full: void
