version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteConfigScript.FaceScript:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            faceID:
              name: faceID
              modifiers:
              - private
              type:
                basic: int
                full: int
            faceName:
              name: faceName
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            layers:
              name: layers
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$ZLayer>
            lightsourceOffsetX:
              name: lightsourceOffsetX
              modifiers:
              - private
              type:
                basic: int
                full: int
            lightsourceOffsetY:
              name: lightsourceOffsetY
              modifiers:
              - private
              type:
                basic: int
                full: int
            lightsourceOffsetZ:
              name: lightsourceOffsetZ
              modifiers:
              - private
              type:
                basic: int
                full: int
            totalHeight:
              name: totalHeight
              modifiers:
              - private
              type:
                basic: int
                full: int
            totalWidth:
              name: totalWidth
              modifiers:
              - private
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - public
          methods:
          - name: getFaceName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getLayer
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: SpriteConfigScript.ZLayer
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$ZLayer
          - name: getLightsourceOffsetX
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getLightsourceOffsetY
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getLightsourceOffsetZ
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getTotalHeight
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getTotalWidth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getVersion
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: IVersionHash
                full: zombie.world.scripts.IVersionHash
            return:
              type:
                basic: void
                full: void
          - name: getZLayers
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
