version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.contextmenuconfig:
        ContextMenuConfigScript:
          extends: zombie.scripting.entity.ComponentScript
          modifiers:
          - public
          fields:
            entries:
              name: entries
              modifiers:
              - protected
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.entity.components.contextmenuconfig.ContextMenuConfigScript$EntryScript>
          constructors:
          - modifiers:
            - private
          methods:
          - name: LoadEntry
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: ScriptParser.Block
                full: zombie.scripting.ScriptParser$Block
            return:
              type:
                basic: ContextMenuConfigScript.EntryScript
                full: zombie.scripting.entity.components.contextmenuconfig.ContextMenuConfigScript$EntryScript
          - name: OnScriptsLoaded
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ScriptLoadMode
                full: zombie.scripting.ScriptLoadMode
            return:
              type:
                basic: void
                full: void
          - name: PreReload
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: copyFrom
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ComponentScript
                full: zombie.scripting.entity.ComponentScript
            return:
              type:
                basic: void
                full: void
          - name: getEntries
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.entity.components.contextmenuconfig.ContextMenuConfigScript$EntryScript>
          - name: load
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ScriptParser.Block
                full: zombie.scripting.ScriptParser$Block
            return:
              type:
                basic: void
                full: void
