version: '1.1'
languages:
  java:
    packages:
      zombie.core.opengl:
        RenderSettings.PlayerRenderSettings:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            BlurFactor:
              name: BlurFactor
              modifiers:
              - private
              type:
                basic: float
                full: float
            CM_Ambient:
              name: CM_Ambient
              modifiers:
              - public
              type:
                basic: float
                full: float
            CM_DayLightStrength:
              name: CM_DayLightStrength
              modifiers:
              - public
              type:
                basic: float
                full: float
            CM_Desaturation:
              name: CM_Desaturation
              modifiers:
              - public
              type:
                basic: float
                full: float
            CM_FogIntensity:
              name: CM_FogIntensity
              modifiers:
              - public
              type:
                basic: float
                full: float
            CM_GlobalLight:
              name: CM_GlobalLight
              modifiers:
              - public
              type:
                basic: ClimateColorInfo
                full: zombie.iso.weather.ClimateColorInfo
            CM_GlobalLightIntensity:
              name: CM_GlobalLightIntensity
              modifiers:
              - public
              type:
                basic: float
                full: float
            CM_NightStrength:
              name: CM_NightStrength
              modifiers:
              - public
              type:
                basic: float
                full: float
            CM_ViewDistance:
              name: CM_ViewDistance
              modifiers:
              - public
              type:
                basic: float
                full: float
            DrunkFactor:
              name: DrunkFactor
              modifiers:
              - private
              type:
                basic: float
                full: float
            SM_Alpha:
              name: SM_Alpha
              modifiers:
              - private
              type:
                basic: float
                full: float
            SM_Radius:
              name: SM_Radius
              modifiers:
              - private
              type:
                basic: float
                full: float
            ambient:
              name: ambient
              modifiers:
              - private
              type:
                basic: float
                full: float
            applyNightVisionGoggles:
              name: applyNightVisionGoggles
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            blendColor:
              name: blendColor
              modifiers:
              - private
              type:
                basic: Color
                full: zombie.core.Color
            blendInfo:
              name: blendInfo
              modifiers:
              - private
              type:
                basic: ColorInfo
                full: zombie.core.textures.ColorInfo
            blendIntensity:
              name: blendIntensity
              modifiers:
              - private
              type:
                basic: float
                full: float
            bmod:
              name: bmod
              modifiers:
              - private
              type:
                basic: float
                full: float
            darkness:
              name: darkness
              modifiers:
              - private
              type:
                basic: float
                full: float
            desaturation:
              name: desaturation
              modifiers:
              - private
              type:
                basic: float
                full: float
            fogMod:
              name: fogMod
              modifiers:
              - private
              type:
                basic: float
                full: float
            gmod:
              name: gmod
              modifiers:
              - private
              type:
                basic: float
                full: float
            goggleMod:
              name: goggleMod
              modifiers:
              - private
              type:
                basic: float
                full: float
            isExterior:
              name: isExterior
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            maskClearColor:
              name: maskClearColor
              modifiers:
              - private
              type:
                basic: Color
                full: zombie.core.Color
            night:
              name: night
              modifiers:
              - private
              type:
                basic: float
                full: float
            rmod:
              name: rmod
              modifiers:
              - private
              type:
                basic: float
                full: float
            viewDistance:
              name: viewDistance
              modifiers:
              - private
              type:
                basic: float
                full: float
          constructors:
          - modifiers:
            - public
          methods:
          - name: applyRenderSettings
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: getAmbient
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getBlendColor
            modifiers:
            - public
            return:
              type:
                basic: Color
                full: zombie.core.Color
          - name: getBlendIntensity
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getBlurFactor
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getBmod
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDarkness
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDesaturation
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDrunkFactor
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getFogMod
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getGmod
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getMaskClearColor
            modifiers:
            - public
            return:
              type:
                basic: Color
                full: zombie.core.Color
          - name: getNight
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getRmod
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getSM_Alpha
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getSM_Radius
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getViewDistance
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: isApplyNightVisionGoggles
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isExterior
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: legacyPostRender
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setBlendColor
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: Color
                full: zombie.core.Color
            return:
              type:
                basic: void
                full: void
          - name: updateRenderSettings
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            - name: arg1
              type:
                basic: IsoPlayer
                full: zombie.characters.IsoPlayer
            return:
              type:
                basic: void
                full: void
