version: '1.1'
languages:
  java:
    packages:
      zombie.network:
        ServerSettings:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            errorMsg:
              name: errorMsg
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            name:
              name: name
              modifiers:
              - protected
              type:
                basic: String
                full: java.lang.String
            sandboxOptions:
              name: sandboxOptions
              modifiers:
              - protected
              type:
                basic: SandboxOptions
                full: zombie.SandboxOptions
            serverOptions:
              name: serverOptions
              modifiers:
              - protected
              type:
                basic: ServerOptions
                full: zombie.network.ServerOptions
            spawnPoints:
              name: spawnPoints
              modifiers:
              - protected
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.network.SpawnRegions$Profession>
            spawnRegions:
              name: spawnRegions
              modifiers:
              - protected
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.network.SpawnRegions$Region>
            valid:
              name: valid
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
          constructors:
          - modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
          methods:
          - name: addSpawnRegion
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
            - name: file
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: clearSpawnRegions
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: deleteFiles
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: duplicateFiles
            modifiers:
            - public
            parameters:
            - name: newName
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: getErrorMsg
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getNumSpawnRegions
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getSandboxOptions
            modifiers:
            - public
            return:
              type:
                basic: SandboxOptions
                full: zombie.SandboxOptions
          - name: getServerOptions
            modifiers:
            - public
            return:
              type:
                basic: ServerOptions
                full: zombie.network.ServerOptions
          - name: getSpawnRegionFile
            modifiers:
            - public
            parameters:
            - name: index
              type:
                basic: int
                full: int
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getSpawnRegionName
            modifiers:
            - public
            parameters:
            - name: index
              type:
                basic: int
                full: int
            return:
              type:
                basic: String
                full: java.lang.String
          - name: isValid
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: loadFiles
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: loadSpawnPointsFile
            modifiers:
            - public
            parameters:
            - name: file
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: KahluaTable
                full: se.krka.kahlua.vm.KahluaTable
          - name: removeSpawnRegion
            modifiers:
            - public
            parameters:
            - name: index
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: rename
            modifiers:
            - public
            parameters:
            - name: newName
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: resetToDefault
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: saveFiles
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: saveSpawnPointsFile
            modifiers:
            - public
            parameters:
            - name: file
              type:
                basic: String
                full: java.lang.String
            - name: professionsTable
              type:
                basic: KahluaTable
                full: se.krka.kahlua.vm.KahluaTable
            return:
              type:
                basic: boolean
                full: boolean
          - name: tryDeleteFile
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
