version: '1.1'
languages:
  java:
    packages:
      zombie.network:
        ServerSettingsManager:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            settings:
              name: settings
              modifiers:
              - protected
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.network.ServerSettings>
            suffixes:
              name: suffixes
              modifiers:
              - protected
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
          staticFields:
            instance:
              name: instance
              modifiers:
              - public
              - static
              type:
                basic: ServerSettingsManager
                full: zombie.network.ServerSettingsManager
          constructors:
          - modifiers:
            - public
          methods:
          - name: anyFilesExist
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: getNameInSettingsFolder
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getSettingsByIndex
            modifiers:
            - public
            parameters:
            - name: index
              type:
                basic: int
                full: int
            return:
              type:
                basic: ServerSettings
                full: zombie.network.ServerSettings
          - name: getSettingsCount
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getSettingsFolder
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getSuffixes
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
          - name: isValidName
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: isValidNewName
            modifiers:
            - public
            parameters:
            - name: newName
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: readAllSettings
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
