version: '1.1'
languages:
  java:
    packages:
      zombie.erosion:
        ErosionConfig:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            debug:
              name: debug
              modifiers:
              - public
              type:
                basic: ErosionConfig.Debug
                full: zombie.erosion.ErosionConfig$Debug
            season:
              name: season
              modifiers:
              - public
              type:
                basic: ErosionConfig.Season
                full: zombie.erosion.ErosionConfig$Season
            seeds:
              name: seeds
              modifiers:
              - public
              type:
                basic: ErosionConfig.Seeds
                full: zombie.erosion.ErosionConfig$Seeds
            time:
              name: time
              modifiers:
              - public
              type:
                basic: ErosionConfig.Time
                full: zombie.erosion.ErosionConfig$Time
          constructors:
          - modifiers:
            - public
          methods:
          - name: consolePrint
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: getDebug
            modifiers:
            - public
            return:
              type:
                basic: ErosionConfig.Debug
                full: zombie.erosion.ErosionConfig$Debug
          - name: load
            modifiers:
            - public
            parameters:
            - name: bb
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: readFile
            modifiers:
            - public
            parameters:
            - name: _file
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: save
            modifiers:
            - public
            parameters:
            - name: bb
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: writeFile
            modifiers:
            - public
            parameters:
            - name: _file
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
