version: '1.1'
languages:
  java:
    packages:
      zombie.erosion:
        ErosionConfig.Time:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            epoch:
              name: epoch
              modifiers:
              - package
              type:
                basic: int
                full: int
            eticks:
              name: eticks
              modifiers:
              - package
              type:
                basic: int
                full: int
            ticks:
              name: ticks
              modifiers:
              - package
              type:
                basic: int
                full: int
            tickunit:
              name: tickunit
              modifiers:
              - package
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - public
