version: '1.1'
languages:
  java:
    packages:
      zombie.erosion:
        ErosionConfig.Seeds:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            seedKudzu_0:
              name: seedKudzu_0
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedKudzu_1:
              name: seedKudzu_1
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedKudzu_2:
              name: seedKudzu_2
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedMain_0:
              name: seedMain_0
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedMain_1:
              name: seedMain_1
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedMain_2:
              name: seedMain_2
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedMinerals_0:
              name: seedMinerals_0
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedMinerals_1:
              name: seedMinerals_1
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedMinerals_2:
              name: seedMinerals_2
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedMoisture_0:
              name: seedMoisture_0
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedMoisture_1:
              name: seedMoisture_1
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedMoisture_2:
              name: seedMoisture_2
              modifiers:
              - package
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - public
