version: '1.1'
languages:
  java:
    packages:
      org.w3c.dom:
        DOMConfiguration:
          extends: java.lang.Object
          modifiers:
          - public
          - abstract
          methods:
          - name: canSetParameter
            modifiers:
            - public
            - abstract
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
              notes: The name of the parameter to check.
            - name: value
              type:
                basic: Object
                full: java.lang.Object
              notes: "An object. if null, the returned value is\n   true."
            return:
              type:
                basic: boolean
                full: boolean
              notes: "true if the parameter could be successfully set\n   to the specified\
                \ value, or false if the parameter is\n   not recognized or the requested\
                \ value is not supported. This does\n   not change the current value\
                \ of the parameter itself."
            notes: Check if setting a parameter to a specific value is supported.
          - name: getParameter
            modifiers:
            - public
            - abstract
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
              notes: The name of the parameter.
            return:
              type:
                basic: Object
                full: java.lang.Object
              notes: "The current object associated with the specified parameter or\n\
                \   null if no object has been associated or if the\n   parameter\
                \ is not supported."
            notes: Return the value of a parameter if known.
          - name: getParameterNames
            modifiers:
            - public
            - abstract
            return:
              type:
                basic: DOMStringList
                full: org.w3c.dom.DOMStringList
            notes: "The list of the parameters supported by this\n DOMConfiguration\
              \ object and for which at least one value\n can be set by the application.\
              \ Note that this list can also contain\n parameter names defined outside\
              \ this specification."
          - name: setParameter
            modifiers:
            - public
            - abstract
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
              notes: The name of the parameter to set.
            - name: value
              type:
                basic: Object
                full: java.lang.Object
              notes: "The new value or null if the user wishes to\n   unset the parameter.\
                \ While the type of the value parameter is\n   defined as DOMUserData,\
                \ the object type must match the\n   type defined by the definition\
                \ of the parameter. For example, if\n   the parameter is \"error-handler\"\
                , the value must be of type\n   DOMErrorHandler."
            return:
              type:
                basic: void
                full: void
            notes: Set the value of a parameter.
