version: '1.1'
languages:
  java:
    packages:
      java.awt:
        GraphicsConfigTemplate:
          extends: java.lang.Object
          modifiers:
          - public
          - abstract
          notes: "The GraphicsConfigTemplate class is used to obtain a valid\n GraphicsConfiguration.\
            \  A user instantiates one of these\n objects and then sets all non-default\
            \ attributes as desired.  The\n GraphicsDevice.getBestConfiguration(java.awt.GraphicsConfigTemplate)\
            \ method found in the\n GraphicsDevice class is then called with this\n\
            \ GraphicsConfigTemplate.  A valid\n GraphicsConfiguration is returned\
            \ that meets or exceeds\n what was requested in the GraphicsConfigTemplate."
          staticFields:
            PREFERRED:
              name: PREFERRED
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
              notes: "Value used for \"Enum\" (Integer) type.  States that this\n\
                \ feature is desired for the GraphicsConfiguration\n object.  A selection\
                \ with this feature is preferred over a\n selection that does not\
                \ include this feature, although both\n selections can be considered\
                \ valid matches."
            REQUIRED:
              name: REQUIRED
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
              notes: "Value used for \"Enum\" (Integer) type.  States that this\n\
                \ feature is required for the GraphicsConfiguration\n object.  If\
                \ this feature is not available, do not select the\n GraphicsConfiguration\
                \ object."
            UNNECESSARY:
              name: UNNECESSARY
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
              notes: "Value used for \"Enum\" (Integer) type.  States that this\n\
                \ feature is not necessary for the selection of the\n GraphicsConfiguration\
                \ object.  A selection\n without this feature is preferred over a\
                \ selection that\n includes this feature since it is not used."
            serialVersionUID:
              name: serialVersionUID
              modifiers:
              - private
              - static
              type:
                basic: long
                full: long
          constructors:
          - modifiers:
            - public
            notes: "This class is an abstract class so only subclasses can be\n instantiated."
          methods:
          - name: getBestConfiguration
            modifiers:
            - public
            - abstract
            parameters:
            - name: gc
              type:
                basic: GraphicsConfiguration
                full: java.awt.GraphicsConfiguration[]
              notes: "the array of GraphicsConfiguration\n objects to choose from."
            return:
              type:
                basic: GraphicsConfiguration
                full: java.awt.GraphicsConfiguration
              notes: "a GraphicsConfiguration object that is\n the best configuration\
                \ possible."
            notes: "Returns the \"best\" configuration possible that passes the\n\
              \ criteria defined in the GraphicsConfigTemplate."
          - name: isGraphicsConfigSupported
            modifiers:
            - public
            - abstract
            parameters:
            - name: gc
              type:
                basic: GraphicsConfiguration
                full: java.awt.GraphicsConfiguration
              notes: the GraphicsConfiguration object to test
            return:
              type:
                basic: boolean
                full: boolean
              notes: "true if this\n GraphicsConfiguration object can be used to create\n\
                \ surfaces that support the indicated features;\n false if the GraphicsConfiguration\
                \ can\n not be used to create a drawing surface usable by this Java(tm)\n\
                \ API."
            notes: "Returns a boolean indicating whether or\n not the specified GraphicsConfiguration\
              \ can be\n used to create a drawing surface that supports the indicated\n\
              \ features."
