version: '1.1'
languages:
  java:
    packages:
      zombie.entity.components.contextmenuconfig:
        ContextMenuConfig:
          extends: zombie.entity.Component
          modifiers:
          - public
          constructors:
          - modifiers:
            - private
          methods:
          - name: getEntries
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.entity.components.contextmenuconfig.ContextMenuConfigScript$EntryScript>
          - name: isQualifiesForMetaStorage
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isValid
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: load
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: arg1
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: loadSyncData
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: onAddedToOwner
            modifiers:
            - protected
            return:
              type:
                basic: void
                full: void
          - name: onComponentEvent
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ComponentEvent
                full: zombie.entity.events.ComponentEvent
            return:
              type:
                basic: void
                full: void
          - name: onConnectComponents
            modifiers:
            - protected
            return:
              type:
                basic: void
                full: void
          - name: onEntityEvent
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: EntityEvent
                full: zombie.entity.events.EntityEvent
            return:
              type:
                basic: void
                full: void
          - name: onFirstCreation
            modifiers:
            - protected
            return:
              type:
                basic: void
                full: void
          - name: onReceivePacket
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: arg1
              type:
                basic: EntityPacketType
                full: zombie.entity.network.EntityPacketType
            - name: arg2
              type:
                basic: UdpConnection
                full: zombie.core.raknet.UdpConnection
            return:
              type:
                basic: boolean
                full: boolean
          - name: onRemovedFromOwner
            modifiers:
            - protected
            return:
              type:
                basic: void
                full: void
          - name: readFromScript
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ComponentScript
                full: zombie.scripting.entity.ComponentScript
            return:
              type:
                basic: void
                full: void
          - name: reset
            modifiers:
            - protected
            return:
              type:
                basic: void
                full: void
          - name: save
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: saveSyncData
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
