version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteConfigScript.XRow:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            tiles:
              name: tiles
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$TileScript>
          constructors:
          - modifiers:
            - public
          methods:
          - name: getTile
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: SpriteConfigScript.TileScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$TileScript
          - name: getVersion
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: IVersionHash
                full: zombie.world.scripts.IVersionHash
            return:
              type:
                basic: void
                full: void
          - name: getWidth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
