version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteConfigScript.TileScript:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            blocksSquare:
              name: blocksSquare
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            isEmptySpace:
              name: isEmptySpace
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            tileName:
              name: tileName
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
          constructors:
          - modifiers:
            - public
          methods:
          - name: getTileName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getVersion
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: IVersionHash
                full: zombie.world.scripts.IVersionHash
            return:
              type:
                basic: void
                full: void
          - name: isBlocksSquare
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isEmptySpace
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
