version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteConfigScript:
          extends: zombie.scripting.entity.ComponentScript
          modifiers:
          - public
          fields:
            OnCreate:
              name: OnCreate
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            OnIsValid:
              name: OnIsValid
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            TimedActionOnIsValid:
              name: TimedActionOnIsValid
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            allTileNames:
              name: allTileNames
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
            bonusHealth:
              name: bonusHealth
              modifiers:
              - private
              type:
                basic: int
                full: int
            breakSound:
              name: breakSound
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            canBePadlocked:
              name: canBePadlocked
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            cornerSprite:
              name: cornerSprite
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            debugItem:
              name: debugItem
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            dontNeedFrame:
              name: dontNeedFrame
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            faces:
              name: faces
              modifiers:
              - private
              type:
                basic: SpriteConfigScript.FaceScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$FaceScript[]
            fuel:
              name: fuel
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            health:
              name: health
              modifiers:
              - private
              type:
                basic: int
                full: int
            isMultiTile:
              name: isMultiTile
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            isPole:
              name: isPole
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            isProp:
              name: isProp
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            isSingleFace:
              name: isSingleFace
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            isThumpable:
              name: isThumpable
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            isValid:
              name: isValid
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            lightRadius:
              name: lightRadius
              modifiers:
              - private
              type:
                basic: int
                full: int
            lightsourceFuel:
              name: lightsourceFuel
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            lightsourceItem:
              name: lightsourceItem
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            lightsourceTagItem:
              name: lightsourceTagItem
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
            needToBeAgainstWall:
              name: needToBeAgainstWall
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            needWindowFrame:
              name: needWindowFrame
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            previousStage:
              name: previousStage
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
            skillBaseHealth:
              name: skillBaseHealth
              modifiers:
              - private
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - private
          methods:
          - name: OnScriptsLoaded
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ScriptLoadMode
                full: zombie.scripting.ScriptLoadMode
            return:
              type:
                basic: void
                full: void
          - name: PreReload
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: checkScripts
            modifiers:
            - private
            return:
              type:
                basic: void
                full: void
          - name: copyFrom
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ComponentScript
                full: zombie.scripting.entity.ComponentScript
            return:
              type:
                basic: void
                full: void
          - name: getAllTileNames
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
          - name: getBonusHealth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getBreakSound
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getCanBePadlocked
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getCornerSprite
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getDebugItem
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getDontNeedFrame
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getFace
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: SpriteConfigScript.FaceScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$FaceScript
          - name: getHealth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getIsThumpable
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getLightRadius
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getLightsourceFuel
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getLightsourceItem
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getLightsourceTagItem
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
          - name: getNeedToBeAgainstWall
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getNeedWindowFrame
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getOnCreate
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getOnIsValid
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getPreviousStages
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
          - name: getSkillBaseHealth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getTimedActionOnIsValid
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getVersion
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IVersionHash
                full: zombie.world.scripts.IVersionHash
            return:
              type:
                basic: void
                full: void
          - name: isMultiTile
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isPole
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isProp
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isSingleFace
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isValid
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isoMasterOnly
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: load
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ScriptParser.Block
                full: zombie.scripting.ScriptParser$Block
            return:
              type:
                basic: void
                full: void
          - name: loadFace
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: SpriteConfigScript.FaceScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$FaceScript
            - name: arg1
              type:
                basic: ScriptParser.Block
                full: zombie.scripting.ScriptParser$Block
            return:
              type:
                basic: void
                full: void
          - name: loadLayer
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: SpriteConfigScript.ZLayer
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$ZLayer
            - name: arg1
              type:
                basic: ScriptParser.Block
                full: zombie.scripting.ScriptParser$Block
            return:
              type:
                basic: void
                full: void
          - name: warnOrError
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
