version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteOverlayConfigScript:
          extends: zombie.scripting.entity.ComponentScript
          modifiers:
          - public
          fields:
            allStyleNames:
              name: allStyleNames
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
            allStyles:
              name: allStyles
              modifiers:
              - private
              type:
                basic: HashMap
                full: java.util.HashMap<java.lang.String, zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$OverlayStyle>
            isValid:
              name: isValid
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
          constructors:
          - modifiers:
            - private
          methods:
          - name: OnScriptsLoaded
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ScriptLoadMode
                full: zombie.scripting.ScriptLoadMode
            return:
              type:
                basic: void
                full: void
          - name: PreReload
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: checkScripts
            modifiers:
            - private
            return:
              type:
                basic: void
                full: void
          - name: copyFrom
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ComponentScript
                full: zombie.scripting.entity.ComponentScript
            return:
              type:
                basic: void
                full: void
          - name: getAllStyleNames
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
          - name: getStyle
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: SpriteOverlayConfigScript.OverlayStyle
                full: zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$OverlayStyle
          - name: getVersion
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IVersionHash
                full: zombie.world.scripts.IVersionHash
            return:
              type:
                basic: void
                full: void
          - name: isValid
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: load
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ScriptParser.Block
                full: zombie.scripting.ScriptParser$Block
            return:
              type:
                basic: void
                full: void
          - name: loadFace
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: SpriteOverlayConfigScript.FaceScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$FaceScript
            - name: arg1
              type:
                basic: ScriptParser.Block
                full: zombie.scripting.ScriptParser$Block
            return:
              type:
                basic: void
                full: void
          - name: loadLayer
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: SpriteOverlayConfigScript.ZLayer
                full: zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$ZLayer
            - name: arg1
              type:
                basic: ScriptParser.Block
                full: zombie.scripting.ScriptParser$Block
            return:
              type:
                basic: void
                full: void
          - name: loadStyle
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: ScriptParser.Block
                full: zombie.scripting.ScriptParser$Block
            return:
              type:
                basic: void
                full: void
          - name: warnOrError
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
