version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteOverlayConfigScript.OverlayStyle:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            allTileNames:
              name: allTileNames
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
            faces:
              name: faces
              modifiers:
              - private
              type:
                basic: SpriteOverlayConfigScript.FaceScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$FaceScript[]
            isMultiTile:
              name: isMultiTile
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            isSingleFace:
              name: isSingleFace
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            isValid:
              name: isValid
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            styleName:
              name: styleName
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
          constructors:
          - modifiers:
            - public
          methods:
          - name: getAllTileNames
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
          - name: getFace
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: SpriteOverlayConfigScript.FaceScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$FaceScript
          - name: getStyleName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getVersion
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: IVersionHash
                full: zombie.world.scripts.IVersionHash
            return:
              type:
                basic: void
                full: void
          - name: isMultiTile
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isSingleFace
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isValid
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          staticMethods:
          - name: copy
            modifiers:
            - private
            - static
            parameters:
            - name: arg0
              type:
                basic: SpriteOverlayConfigScript.OverlayStyle
                full: zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$OverlayStyle
            return:
              type:
                basic: SpriteOverlayConfigScript.OverlayStyle
                full: zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$OverlayStyle
