version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteOverlayConfigScript.FaceScript:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            faceID:
              name: faceID
              modifiers:
              - private
              type:
                basic: int
                full: int
            faceName:
              name: faceName
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            layers:
              name: layers
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$ZLayer>
            totalHeight:
              name: totalHeight
              modifiers:
              - private
              type:
                basic: int
                full: int
            totalWidth:
              name: totalWidth
              modifiers:
              - private
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - public
          methods:
          - name: getFaceID
            modifiers:
            - protected
            return:
              type:
                basic: int
                full: int
          - name: getFaceName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getLayer
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: SpriteOverlayConfigScript.ZLayer
                full: zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$ZLayer
          - name: getTotalHeight
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getTotalWidth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getVersion
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: IVersionHash
                full: zombie.world.scripts.IVersionHash
            return:
              type:
                basic: void
                full: void
          - name: getZLayers
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          staticMethods:
          - name: copy
            modifiers:
            - private
            - static
            parameters:
            - name: arg0
              type:
                basic: SpriteOverlayConfigScript.FaceScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$FaceScript
            return:
              type:
                basic: SpriteOverlayConfigScript.FaceScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteOverlayConfigScript$FaceScript
