version: '1.1'
languages:
  java:
    packages:
      zombie.vehicles:
        EditVehicleState.LuaEnvironment:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            caller:
              name: caller
              modifiers:
              - public
              type:
                basic: LuaCaller
                full: se.krka.kahlua.integration.LuaCaller
            env:
              name: env
              modifiers:
              - public
              type:
                basic: KahluaTable
                full: se.krka.kahlua.vm.KahluaTable
            platform:
              name: platform
              modifiers:
              - public
              type:
                basic: J2SEPlatform
                full: se.krka.kahlua.j2se.J2SEPlatform
            thread:
              name: thread
              modifiers:
              - public
              type:
                basic: KahluaThread
                full: se.krka.kahlua.vm.KahluaThread
          constructors:
          - modifiers:
            - public
            parameters:
            - name: platform
              type:
                basic: J2SEPlatform
                full: se.krka.kahlua.j2se.J2SEPlatform
            - name: converterManager
              type:
                basic: KahluaConverterManager
                full: se.krka.kahlua.converter.KahluaConverterManager
            - name: env
              type:
                basic: KahluaTable
                full: se.krka.kahlua.vm.KahluaTable
