version: '1.1'
languages:
  java:
    packages:
      zombie.worldMap:
        WorldMapSettings:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            mMiniMap:
              name: mMiniMap
              modifiers:
              - package
              type:
                basic: WorldMapSettings.MiniMap
                full: zombie.worldMap.WorldMapSettings$MiniMap
            mWorldMap:
              name: mWorldMap
              modifiers:
              - package
              type:
                basic: WorldMapSettings.WorldMap
                full: zombie.worldMap.WorldMapSettings$WorldMap
            m_options:
              name: m_options
              modifiers:
              - package
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.config.ConfigOption>
            m_readVersion:
              name: m_readVersion
              modifiers:
              - private
              type:
                basic: int
                full: int
          staticFields:
            VERSION:
              name: VERSION
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            VERSION1:
              name: VERSION1
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            instance:
              name: instance
              modifiers:
              - private
              - static
              type:
                basic: WorldMapSettings
                full: zombie.worldMap.WorldMapSettings
          constructors:
          - modifiers:
            - public
          methods:
          - name: getBoolean
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: getDouble
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
            - name: defaultValue
              type:
                basic: double
                full: double
            return:
              type:
                basic: double
                full: double
          - name: getFileVersion
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getOptionByIndex
            modifiers:
            - public
            parameters:
            - name: index
              type:
                basic: int
                full: int
            return:
              type:
                basic: ConfigOption
                full: zombie.config.ConfigOption
          - name: getOptionByName
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: ConfigOption
                full: zombie.config.ConfigOption
          - name: getOptionCount
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: load
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: newOption
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
          - name: newOption
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: double
                full: double
            - name: arg2
              type:
                basic: double
                full: double
            - name: arg3
              type:
                basic: double
                full: double
            return:
              type:
                basic: DoubleConfigOption
                full: zombie.config.DoubleConfigOption
          - name: save
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: setBoolean
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
            - name: value
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setDouble
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
            - name: value
              type:
                basic: double
                full: double
            return:
              type:
                basic: void
                full: void
          staticMethods:
          - name: Reset
            modifiers:
            - public
            - static
            return:
              type:
                basic: void
                full: void
          - name: getInstance
            modifiers:
            - public
            - static
            return:
              type:
                basic: WorldMapSettings
                full: zombie.worldMap.WorldMapSettings
