version: '1.1'
languages:
  java:
    packages:
      zombie.worldMap:
        WorldMapSettings.WorldMap:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            CenterX:
              name: CenterX
              modifiers:
              - public
              type:
                basic: DoubleConfigOption
                full: zombie.config.DoubleConfigOption
            CenterY:
              name: CenterY
              modifiers:
              - public
              type:
                basic: DoubleConfigOption
                full: zombie.config.DoubleConfigOption
            HighlightStreet:
              name: HighlightStreet
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            Isometric:
              name: Isometric
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            LargeStreetLabel:
              name: LargeStreetLabel
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            PlaceNames:
              name: PlaceNames
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            Players:
              name: Players
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            ShowPrintMedia:
              name: ShowPrintMedia
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            ShowStreetNames:
              name: ShowStreetNames
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            ShowSymbolsUI:
              name: ShowSymbolsUI
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            Symbols:
              name: Symbols
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            TerrainImage:
              name: TerrainImage
              modifiers:
              - public
              type:
                basic: BooleanConfigOption
                full: zombie.config.BooleanConfigOption
            Zoom:
              name: Zoom
              modifiers:
              - public
              type:
                basic: DoubleConfigOption
                full: zombie.config.DoubleConfigOption
            this$0:
              name: this$0
              modifiers:
              - package
              type:
                basic: WorldMapSettings
                full: zombie.worldMap.WorldMapSettings
          constructors:
          - modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: WorldMapSettings
                full: zombie.worldMap.WorldMapSettings
