version: '1.1'
languages:
  java:
    packages:
      zombie.entity.components.ui:
        UiConfig:
          extends: zombie.entity.Component
          modifiers:
          - public
          fields:
            entityStyleName:
              name: entityStyleName
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            skin:
              name: skin
              modifiers:
              - private
              type:
                basic: XuiSkin
                full: zombie.scripting.ui.XuiSkin
            uiEnabled:
              name: uiEnabled
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            xuiSkinName:
              name: xuiSkinName
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
          constructors:
          - modifiers:
            - private
          methods:
          - name: getEntityDisplayName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getEntityStyleName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getEntityUiStyle
            modifiers:
            - public
            return:
              type:
                basic: XuiSkin.EntityUiStyle
                full: zombie.scripting.ui.XuiSkin$EntityUiStyle
          - name: getSkin
            modifiers:
            - public
            return:
              type:
                basic: XuiSkin
                full: zombie.scripting.ui.XuiSkin
          - name: getSkin
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: XuiSkin
                full: zombie.scripting.ui.XuiSkin
          - name: getSkinOrDefault
            modifiers:
            - public
            return:
              type:
                basic: XuiSkin
                full: zombie.scripting.ui.XuiSkin
          - name: isUiEnabled
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: load
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: arg1
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: loadSyncData
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: onReceivePacket
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: arg1
              type:
                basic: EntityPacketType
                full: zombie.entity.network.EntityPacketType
            - name: arg2
              type:
                basic: UdpConnection
                full: zombie.core.raknet.UdpConnection
            return:
              type:
                basic: boolean
                full: boolean
          - name: readFromScript
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ComponentScript
                full: zombie.scripting.entity.ComponentScript
            return:
              type:
                basic: void
                full: void
          - name: reset
            modifiers:
            - protected
            return:
              type:
                basic: void
                full: void
          - name: save
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: saveSyncData
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: setSkin
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
