version: '1.1'
languages:
  java:
    packages:
      zombie.audio:
        MusicIntensityConfig:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            m_eventById:
              name: m_eventById
              modifiers:
              - private
              type:
                basic: HashMap
                full: java.util.HashMap<java.lang.String, zombie.audio.MusicIntensityConfig$Event>
            m_events:
              name: m_events
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.audio.MusicIntensityConfig$Event>
          staticFields:
            instance:
              name: instance
              modifiers:
              - private
              - static
              type:
                basic: MusicIntensityConfig
                full: zombie.audio.MusicIntensityConfig
          constructors:
          - modifiers:
            - public
          methods:
          - name: checkHealthPanelVisible
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IsoGameCharacter
                full: zombie.characters.IsoGameCharacter
            return:
              type:
                basic: void
                full: void
          - name: checkHealthPanel_SeeBite
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: IsoPlayer
                full: zombie.characters.IsoPlayer
            return:
              type:
                basic: void
                full: void
          - name: initEvents
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: KahluaTableImpl
                full: se.krka.kahlua.j2se.KahluaTableImpl
            return:
              type:
                basic: void
                full: void
          - name: restoreToFullHealth
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IsoGameCharacter
                full: zombie.characters.IsoGameCharacter
            return:
              type:
                basic: void
                full: void
          - name: triggerEvent
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: MusicIntensityEvents
                full: zombie.audio.MusicIntensityEvents
            return:
              type:
                basic: MusicIntensityEvent
                full: zombie.audio.MusicIntensityEvent
          staticMethods:
          - name: getInstance
            modifiers:
            - public
            - static
            return:
              type:
                basic: MusicIntensityConfig
                full: zombie.audio.MusicIntensityConfig
