version: '1.1'
languages:
  java:
    packages:
      zombie.iso.worldgen.zones:
        AnimalsPathConfig:
          extends: java.lang.Record
          modifiers:
          - public
          - final
          fields:
            animalType:
              name: animalType
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            chance:
              name: chance
              modifiers:
              - private
              type:
                basic: float
                full: float
            count:
              name: count
              modifiers:
              - private
              type:
                basic: int
                full: int
            extension:
              name: extension
              modifiers:
              - private
              type:
                basic: int
                full: int[]
            extensionChance:
              name: extensionChance
              modifiers:
              - private
              type:
                basic: float
                full: float
            points:
              name: points
              modifiers:
              - private
              type:
                basic: int
                full: int[]
            radius:
              name: radius
              modifiers:
              - private
              type:
                basic: int
                full: int[]
          constructors:
          - modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: float
                full: float
            - name: arg3
              type:
                basic: int
                full: int[]
            - name: arg4
              type:
                basic: int
                full: int[]
            - name: arg5
              type:
                basic: int
                full: int[]
            - name: arg6
              type:
                basic: float
                full: float
          methods:
          - name: animalType
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: chance
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: count
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: equals
            modifiers:
            - public
            - final
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: boolean
                full: boolean
          - name: extension
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int[]
          - name: extensionChance
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getNameHash
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: hashCode
            modifiers:
            - public
            - final
            return:
              type:
                basic: int
                full: int
          - name: points
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int[]
          - name: radius
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int[]
          - name: toString
            modifiers:
            - public
            - final
            return:
              type:
                basic: String
                full: java.lang.String
