version: '1.1'
languages:
  java:
    packages:
      se.krka.kahlua.integration.expose:
        ReturnValues:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            args:
              name: args
              modifiers:
              - private
              type:
                basic: int
                full: int
            callFrame:
              name: callFrame
              modifiers:
              - private
              type:
                basic: LuaCallFrame
                full: se.krka.kahlua.vm.LuaCallFrame
            manager:
              name: manager
              modifiers:
              - private
              type:
                basic: KahluaConverterManager
                full: se.krka.kahlua.converter.KahluaConverterManager
          staticFields:
            INITIAL_POOL_SIZE:
              name: INITIAL_POOL_SIZE
              modifiers:
              - private
              - static
              type:
                basic: int
                full: int
            Pool:
              name: Pool
              modifiers:
              - private
              - static
              type:
                basic: ArrayList
                full: java.util.ArrayList<se.krka.kahlua.integration.expose.ReturnValues>
            minPoolSize:
              name: minPoolSize
              modifiers:
              - private
              - static
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - package
            parameters:
            - name: arg0
              type:
                basic: KahluaConverterManager
                full: se.krka.kahlua.converter.KahluaConverterManager
            - name: arg1
              type:
                basic: LuaCallFrame
                full: se.krka.kahlua.vm.LuaCallFrame
          methods:
          - name: getNArguments
            modifiers:
            - package
            return:
              type:
                basic: int
                full: int
          - name: push
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: ReturnValues
                full: se.krka.kahlua.integration.expose.ReturnValues
          - name: push
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object[]
            return:
              type:
                basic: ReturnValues
                full: se.krka.kahlua.integration.expose.ReturnValues
          staticMethods:
          - name: get
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: KahluaConverterManager
                full: se.krka.kahlua.converter.KahluaConverterManager
            - name: arg1
              type:
                basic: LuaCallFrame
                full: se.krka.kahlua.vm.LuaCallFrame
            return:
              type:
                basic: ReturnValues
                full: se.krka.kahlua.integration.expose.ReturnValues
          - name: put
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: ReturnValues
                full: se.krka.kahlua.integration.expose.ReturnValues
            return:
              type:
                basic: void
                full: void
