version: '1.1'
languages:
  java:
    packages:
      zombie.iso.worldgen.veins:
        OreVeinConfig:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            armsAmountMax:
              name: armsAmountMax
              modifiers:
              - private
              type:
                basic: int
                full: int
            armsAmountMin:
              name: armsAmountMin
              modifiers:
              - private
              type:
                basic: int
                full: int
            armsDeltaAngle:
              name: armsDeltaAngle
              modifiers:
              - private
              type:
                basic: int
                full: int
            armsDistMax:
              name: armsDistMax
              modifiers:
              - private
              type:
                basic: int
                full: int
            armsDistMin:
              name: armsDistMin
              modifiers:
              - private
              type:
                basic: int
                full: int
            armsProb:
              name: armsProb
              modifiers:
              - private
              type:
                basic: float
                full: float
            centerProb:
              name: centerProb
              modifiers:
              - private
              type:
                basic: float
                full: float
            centerRadius:
              name: centerRadius
              modifiers:
              - private
              type:
                basic: int
                full: int
            probability:
              name: probability
              modifiers:
              - private
              type:
                basic: float
                full: float
            tiles:
              name: tiles
              modifiers:
              - private
              type:
                basic: List
                full: java.util.List<zombie.iso.worldgen.biomes.TileGroup>
          constructors:
          - modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: List
                full: java.util.List<zombie.iso.worldgen.biomes.TileGroup>
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: float
                full: float
            - name: arg3
              type:
                basic: int
                full: int
            - name: arg4
              type:
                basic: int
                full: int
            - name: arg5
              type:
                basic: int
                full: int
            - name: arg6
              type:
                basic: int
                full: int
            - name: arg7
              type:
                basic: int
                full: int
            - name: arg8
              type:
                basic: float
                full: float
            - name: arg9
              type:
                basic: float
                full: float
          methods:
          - name: getArmsAmountMax
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getArmsAmountMin
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getArmsDeltaAngle
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getArmsDistMax
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getArmsDistMin
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getArmsProb
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getCenterProb
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getCenterRadius
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getProbability
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getTiles
            modifiers:
            - public
            return:
              type:
                basic: List
                full: java.util.List<zombie.iso.worldgen.biomes.TileGroup>
