version: '1.1'
languages:
  java:
    packages:
      zombie.entity.components.spriteconfig:
        SpriteConfig:
          extends: zombie.entity.Component
          modifiers:
          - public
          fields:
            configScript:
              name: configScript
              modifiers:
              - private
              type:
                basic: SpriteConfigScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript
            faceInfo:
              name: faceInfo
              modifiers:
              - private
              type:
                basic: SpriteConfigManager.FaceInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$FaceInfo
            objectInfo:
              name: objectInfo
              modifiers:
              - private
              type:
                basic: SpriteConfigManager.ObjectInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$ObjectInfo
            tileInfo:
              name: tileInfo
              modifiers:
              - private
              type:
                basic: SpriteConfigManager.TileInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo
            wasLoadedAsMaster:
              name: wasLoadedAsMaster
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
          constructors:
          - modifiers:
            - private
          methods:
          - name: findAllMultiSquareObjects
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.iso.IsoObject>
            return:
              type:
                basic: boolean
                full: boolean
          - name: getAllMultiSquareObjects
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.iso.IsoObject>
            return:
              type:
                basic: boolean
                full: boolean
          - name: getFaceInfo
            modifiers:
            - public
            return:
              type:
                basic: SpriteConfigManager.FaceInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$FaceInfo
          - name: getMasterOffsetX
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMasterOffsetY
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMasterOffsetZ
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMultiSquareMaster
            modifiers:
            - public
            return:
              type:
                basic: IsoObject
                full: zombie.iso.IsoObject
          - name: getObjectInfo
            modifiers:
            - public
            return:
              type:
                basic: SpriteConfigManager.ObjectInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$ObjectInfo
          - name: getTileInfo
            modifiers:
            - public
            return:
              type:
                basic: SpriteConfigManager.TileInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo
          - name: initObjectInfo
            modifiers:
            - private
            return:
              type:
                basic: void
                full: void
          - name: isCanRotate
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isMultiSquareFullyLoaded
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isMultiSquareMaster
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isMultiSquareSlave
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isValid
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isValidMultiSquare
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isWasLoadedAsMaster
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: load
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: arg1
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: loadSyncData
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: onAddedToOwner
            modifiers:
            - protected
            return:
              type:
                basic: void
                full: void
          - name: onReceivePacket
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: arg1
              type:
                basic: EntityPacketType
                full: zombie.entity.network.EntityPacketType
            - name: arg2
              type:
                basic: UdpConnection
                full: zombie.core.raknet.UdpConnection
            return:
              type:
                basic: boolean
                full: boolean
          - name: onRemovedFromOwner
            modifiers:
            - protected
            return:
              type:
                basic: void
                full: void
          - name: readFromScript
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ComponentScript
                full: zombie.scripting.entity.ComponentScript
            return:
              type:
                basic: void
                full: void
          - name: reset
            modifiers:
            - protected
            return:
              type:
                basic: void
                full: void
          - name: resetObjectInfo
            modifiers:
            - private
            return:
              type:
                basic: void
                full: void
          - name: save
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: saveSyncData
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
