version: '1.1'
languages:
  java:
    packages:
      zombie.entity.components.spriteconfig:
        SpriteConfigManager.TileInfo:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            blocking:
              name: blocking
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            empty:
              name: empty
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            master:
              name: master
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            masterOffsetX:
              name: masterOffsetX
              modifiers:
              - private
              type:
                basic: int
                full: int
            masterOffsetY:
              name: masterOffsetY
              modifiers:
              - private
              type:
                basic: int
                full: int
            masterOffsetZ:
              name: masterOffsetZ
              modifiers:
              - private
              type:
                basic: int
                full: int
            tile_sprite:
              name: tile_sprite
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            x:
              name: x
              modifiers:
              - private
              type:
                basic: int
                full: int
            y:
              name: y
              modifiers:
              - private
              type:
                basic: int
                full: int
            z:
              name: z
              modifiers:
              - private
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: int
                full: int
            - name: arg3
              type:
                basic: int
                full: int
            - name: arg4
              type:
                basic: boolean
                full: boolean
            - name: arg5
              type:
                basic: boolean
                full: boolean
            - name: arg6
              type:
                basic: boolean
                full: boolean
          methods:
          - name: getMasterOffsetX
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMasterOffsetY
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMasterOffsetZ
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getSpriteName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getX
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getY
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getZ
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: isBlocking
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isEmpty
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isMaster
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: verifyObject
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IsoObject
                full: zombie.iso.IsoObject
            return:
              type:
                basic: boolean
                full: boolean
