version: '1.1'
languages:
  java:
    packages:
      zombie.entity.components.spriteconfig:
        SpriteConfigManager:
          extends: java.lang.Object
          modifiers:
          - public
          staticFields:
            FACE_E:
              name: FACE_E
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            FACE_ID_CARDINAL_MAX:
              name: FACE_ID_CARDINAL_MAX
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            FACE_ID_E:
              name: FACE_ID_E
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            FACE_ID_MAX:
              name: FACE_ID_MAX
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            FACE_ID_N:
              name: FACE_ID_N
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            FACE_ID_N_OPEN:
              name: FACE_ID_N_OPEN
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            FACE_ID_S:
              name: FACE_ID_S
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            FACE_ID_SINGLE:
              name: FACE_ID_SINGLE
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            FACE_ID_W:
              name: FACE_ID_W
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            FACE_ID_W_OPEN:
              name: FACE_ID_W_OPEN
              modifiers:
              - public
              - static
              type:
                basic: int
                full: int
            FACE_N:
              name: FACE_N
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            FACE_N_OPEN:
              name: FACE_N_OPEN
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            FACE_S:
              name: FACE_S
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            FACE_SINGLE:
              name: FACE_SINGLE
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            FACE_W:
              name: FACE_W
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            FACE_W_OPEN:
              name: FACE_W_OPEN
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            hasLoadErrors:
              name: hasLoadErrors
              modifiers:
              - private
              - static
              type:
                basic: boolean
                full: boolean
            objectInfos:
              name: objectInfos
              modifiers:
              - private
              - static
              type:
                basic: HashMap
                full: java.util.HashMap<java.lang.String, zombie.entity.components.spriteconfig.SpriteConfigManager$ObjectInfo>
            objectInfosList:
              name: objectInfosList
              modifiers:
              - private
              - static
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.entity.components.spriteconfig.SpriteConfigManager$ObjectInfo>
            registeredScriptedSprites:
              name: registeredScriptedSprites
              modifiers:
              - private
              - static
              type:
                basic: HashSet
                full: java.util.HashSet<zombie.iso.sprite.IsoSprite>
            tempFaceSprites:
              name: tempFaceSprites
              modifiers:
              - private
              - static
              type:
                basic: HashSet
                full: java.util.HashSet<java.lang.String>
          constructors:
          - modifiers:
            - public
          staticMethods:
          - name: GetFaceIdForString
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: int
                full: int
          - name: GetObjectInfo
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: SpriteConfigManager.ObjectInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$ObjectInfo
          - name: GetObjectInfoList
            modifiers:
            - public
            - static
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.entity.components.spriteconfig.SpriteConfigManager$ObjectInfo>
          - name: HasLoadErrors
            modifiers:
            - public
            - static
            return:
              type:
                basic: boolean
                full: boolean
          - name: InitScriptsPostTileDef
            modifiers:
            - public
            - static
            return:
              type:
                basic: void
                full: void
          - name: Reset
            modifiers:
            - public
            - static
            return:
              type:
                basic: void
                full: void
          - name: getObjectInfoFromSprite
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: SpriteConfigManager.ObjectInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$ObjectInfo
          - name: parseEntityScript
            modifiers:
            - private
            - static
            parameters:
            - name: arg0
              type:
                basic: GameEntityScript
                full: zombie.scripting.entity.GameEntityScript
            return:
              type:
                basic: void
                full: void
          - name: parseSpriteConfigScript
            modifiers:
            - private
            - static
            parameters:
            - name: arg0
              type:
                basic: SpriteConfigScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript
            return:
              type:
                basic: boolean
                full: boolean
