version: '1.1'
languages:
  java:
    packages:
      zombie.iso.worldgen.roads:
        RoadConfig:
          extends: java.lang.Record
          modifiers:
          - public
          - final
          fields:
            filter:
              name: filter
              modifiers:
              - private
              type:
                basic: double
                full: double
            probaRoads:
              name: probaRoads
              modifiers:
              - private
              type:
                basic: double
                full: double
            probability:
              name: probability
              modifiers:
              - private
              type:
                basic: double
                full: double
            tiles:
              name: tiles
              modifiers:
              - private
              type:
                basic: List
                full: java.util.List<zombie.iso.worldgen.biomes.TileGroup>
          constructors:
          - modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: List
                full: java.util.List<zombie.iso.worldgen.biomes.TileGroup>
            - name: arg1
              type:
                basic: double
                full: double
            - name: arg2
              type:
                basic: double
                full: double
            - name: arg3
              type:
                basic: double
                full: double
          methods:
          - name: equals
            modifiers:
            - public
            - final
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: boolean
                full: boolean
          - name: filter
            modifiers:
            - public
            return:
              type:
                basic: double
                full: double
          - name: hashCode
            modifiers:
            - public
            - final
            return:
              type:
                basic: int
                full: int
          - name: probaRoads
            modifiers:
            - public
            return:
              type:
                basic: double
                full: double
          - name: probability
            modifiers:
            - public
            return:
              type:
                basic: double
                full: double
          - name: tiles
            modifiers:
            - public
            return:
              type:
                basic: List
                full: java.util.List<zombie.iso.worldgen.biomes.TileGroup>
          - name: toString
            modifiers:
            - public
            - final
            return:
              type:
                basic: String
                full: java.lang.String
