version: '1.1'
languages:
  java:
    packages:
      zombie.iso.fboRenderChunk:
        FBORenderTracerEffects.DoubleConfigOption1:
          extends: zombie.config.DoubleConfigOption
          modifiers:
          - public
          fields:
            this$0:
              name: this$0
              modifiers:
              - package
              type:
                basic: FBORenderTracerEffects
                full: zombie.iso.fboRenderChunk.FBORenderTracerEffects
          constructors:
          - modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: FBORenderTracerEffects
                full: zombie.iso.fboRenderChunk.FBORenderTracerEffects
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            - name: arg2
              type:
                basic: double
                full: double
            - name: arg3
              type:
                basic: double
                full: double
            - name: arg4
              type:
                basic: double
                full: double
