version: '1.1'
languages:
  java:
    packages:
      zombie.erosion:
        ErosionConfig.Season:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            apr:
              name: apr
              modifiers:
              - package
              type:
                basic: float
                full: float
            aug:
              name: aug
              modifiers:
              - package
              type:
                basic: float
                full: float
            dec:
              name: dec
              modifiers:
              - package
              type:
                basic: float
                full: float
            feb:
              name: feb
              modifiers:
              - package
              type:
                basic: float
                full: float
            jan:
              name: jan
              modifiers:
              - package
              type:
                basic: float
                full: float
            jul:
              name: jul
              modifiers:
              - package
              type:
                basic: float
                full: float
            jun:
              name: jun
              modifiers:
              - package
              type:
                basic: float
                full: float
            lat:
              name: lat
              modifiers:
              - package
              type:
                basic: int
                full: int
            mar:
              name: mar
              modifiers:
              - package
              type:
                basic: float
                full: float
            may:
              name: may
              modifiers:
              - package
              type:
                basic: float
                full: float
            noon:
              name: noon
              modifiers:
              - package
              type:
                basic: float
                full: float
            nov:
              name: nov
              modifiers:
              - package
              type:
                basic: float
                full: float
            oct:
              name: oct
              modifiers:
              - package
              type:
                basic: float
                full: float
            seasonLag:
              name: seasonLag
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedA:
              name: seedA
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedB:
              name: seedB
              modifiers:
              - package
              type:
                basic: int
                full: int
            seedC:
              name: seedC
              modifiers:
              - package
              type:
                basic: int
                full: int
            sep:
              name: sep
              modifiers:
              - package
              type:
                basic: float
                full: float
            tempDiff:
              name: tempDiff
              modifiers:
              - package
              type:
                basic: int
                full: int
            tempMax:
              name: tempMax
              modifiers:
              - package
              type:
                basic: int
                full: int
            tempMin:
              name: tempMin
              modifiers:
              - package
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - public
