version: '1.1'
languages:
  java:
    packages:
      org.w3c.dom:
        DOMConfiguration:
          extends: java.lang.Object
          modifiers:
          - public
          - abstract
          methods:
          - name: canSetParameter
            modifiers:
            - public
            - abstract
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: boolean
                full: boolean
          - name: getParameter
            modifiers:
            - public
            - abstract
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: Object
                full: java.lang.Object
          - name: getParameterNames
            modifiers:
            - public
            - abstract
            return:
              type:
                basic: DOMStringList
                full: org.w3c.dom.DOMStringList
          - name: setParameter
            modifiers:
            - public
            - abstract
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: void
                full: void
