version: '1.1'
languages:
  java:
    packages:
      zombie.config:
        EnumConfigOption:
          extends: zombie.config.IntegerConfigOption
          modifiers:
          - public
          constructors:
          - modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
            - name: numValues
              type:
                basic: int
                full: int
            - name: defaultValue
              type:
                basic: int
                full: int
          methods:
          - name: getNumValues
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getType
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
