version: '1.1'
languages:
  java:
    packages:
      zombie.config:
        IntegerConfigOption:
          extends: zombie.config.ConfigOption
          modifiers:
          - public
          fields:
            defaultValue:
              name: defaultValue
              modifiers:
              - protected
              type:
                basic: int
                full: int
            max:
              name: max
              modifiers:
              - protected
              type:
                basic: int
                full: int
            min:
              name: min
              modifiers:
              - protected
              type:
                basic: int
                full: int
            value:
              name: value
              modifiers:
              - protected
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
                full: java.lang.String
            - name: min
              type:
                basic: int
                full: int
            - name: max
              type:
                basic: int
                full: int
            - name: defaultValue
              type:
                basic: int
                full: int
          methods:
          - name: getDefaultValue
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMax
            modifiers:
            - public
            return:
              type:
                basic: double
                full: double
          - name: getMin
            modifiers:
            - public
            return:
              type:
                basic: double
                full: double
          - name: getTooltip
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getType
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getValue
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getValueAsObject
            modifiers:
            - public
            return:
              type:
                basic: Object
                full: java.lang.Object
          - name: getValueAsString
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: isValidString
            modifiers:
            - public
            parameters:
            - name: s
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: makeCopy
            modifiers:
            - public
            return:
              type:
                basic: ConfigOption
                full: zombie.config.ConfigOption
          - name: parse
            modifiers:
            - public
            parameters:
            - name: s
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: resetToDefault
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: setDefaultToCurrentValue
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: setValue
            modifiers:
            - public
            parameters:
            - name: value
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setValueFromObject
            modifiers:
            - public
            parameters:
            - name: o
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: void
                full: void
