version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.itemConfig:
        ItemConfig:
          extends: zombie.scripting.objects.BaseScriptObject
          modifiers:
          - public
          fields:
            hasBeenParsed:
              name: hasBeenParsed
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            includes:
              name: includes
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
            isValid:
              name: isValid
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            name:
              name: name
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            rootScripts:
              name: rootScripts
              modifiers:
              - private
              type:
                basic: HashMap
                full: java.util.HashMap<java.lang.String, zombie.scripting.itemConfig.script.BucketRootScript>
            roots:
              name: roots
              modifiers:
              - private
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.itemConfig.BucketRoot>
            variables:
              name: variables
              modifiers:
              - private
              type:
                basic: HashMap
                full: java.util.HashMap<java.lang.String, java.lang.String>
          staticFields:
            VARIABLE_PREFIX:
              name: VARIABLE_PREFIX
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            error_bucket:
              name: error_bucket
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            error_item_config:
              name: error_item_config
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            error_line:
              name: error_line
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            error_root:
              name: error_root
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            tempGenerators:
              name: tempGenerators
              modifiers:
              - private
              - static
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.itemConfig.RandomGenerator>
          constructors:
          - modifiers:
            - public
          methods:
          - name: BuildBuckets
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: ConfigureEntityOnCreate
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: GameEntity
                full: zombie.entity.GameEntity
            return:
              type:
                basic: void
                full: void
          - name: ConfigureEntitySpawned
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: GameEntity
                full: zombie.entity.GameEntity
            - name: arg1
              type:
                basic: ItemPickInfo
                full: zombie.inventory.ItemPickInfo
            return:
              type:
                basic: void
                full: void
          - name: Load
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: OnScriptsLoaded
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ScriptLoadMode
                full: zombie.scripting.ScriptLoadMode
            return:
              type:
                basic: void
                full: void
          - name: Parse
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: HashSet
                full: java.util.HashSet<java.lang.String>
            return:
              type:
                basic: void
                full: void
          - name: PreReload
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: buildBoolGenerator
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: AttributeType
                full: zombie.entity.components.attributes.AttributeType
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: RandomGenerator
                full: zombie.scripting.itemConfig.RandomGenerator
          - name: buildBucket
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: BucketRootScript
                full: zombie.scripting.itemConfig.script.BucketRootScript
            - name: arg1
              type:
                basic: SelectorBucketScript
                full: zombie.scripting.itemConfig.script.SelectorBucketScript
            return:
              type:
                basic: SelectorBucket
                full: zombie.scripting.itemConfig.SelectorBucket
          - name: buildBucketRoot
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: BucketRootScript
                full: zombie.scripting.itemConfig.script.BucketRootScript
            return:
              type:
                basic: BucketRoot
                full: zombie.scripting.itemConfig.BucketRoot
          - name: buildEnumGenerator
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: AttributeType
                full: zombie.entity.components.attributes.AttributeType
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: RandomGenerator
                full: zombie.scripting.itemConfig.RandomGenerator
          - name: buildEnumSetGenerator
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: AttributeType
                full: zombie.entity.components.attributes.AttributeType
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: RandomGenerator
                full: zombie.scripting.itemConfig.RandomGenerator
          - name: buildEnumStringSetGenerator
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: AttributeType
                full: zombie.entity.components.attributes.AttributeType
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: RandomGenerator
                full: zombie.scripting.itemConfig.RandomGenerator
          - name: buildFluidContainerGenerator
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: RandomGenerator
                full: zombie.scripting.itemConfig.RandomGenerator
          - name: buildLuaFuncGenerator
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: RandomGenerator
                full: zombie.scripting.itemConfig.RandomGenerator
          - name: buildNumericGenerator
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: AttributeType
                full: zombie.entity.components.attributes.AttributeType
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: RandomGenerator
                full: zombie.scripting.itemConfig.RandomGenerator
          - name: buildStringGenerator
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: AttributeType
                full: zombie.entity.components.attributes.AttributeType
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: RandomGenerator
                full: zombie.scripting.itemConfig.RandomGenerator
          - name: getName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: isValid
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          staticMethods:
          - name: MergeRoots
            modifiers:
            - private
            - static
            parameters:
            - name: arg0
              type:
                basic: HashMap
                full: java.util.HashMap<java.lang.String, zombie.scripting.itemConfig.script.BucketRootScript>
            - name: arg1
              type:
                basic: HashMap
                full: java.util.HashMap<java.lang.String, zombie.scripting.itemConfig.script.BucketRootScript>
            - name: arg2
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: HashMap
                full: java.util.HashMap<java.lang.String, zombie.scripting.itemConfig.script.BucketRootScript>
          - name: WarnOrError
            modifiers:
            - private
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: createErrorString
            modifiers:
            - private
            - static
            return:
              type:
                basic: String
                full: java.lang.String
