version: '1.1'
languages:
  java:
    packages:
      zombie.chat:
        ChatSettings.FontSize:
          extends: java.lang.Enum<zombie.chat.ChatSettings$FontSize>
          modifiers:
          - public
          - final
          staticFields:
            $VALUES:
              name: $VALUES
              modifiers:
              - private
              - static
              type:
                basic: ChatSettings.FontSize
                full: zombie.chat.ChatSettings$FontSize[]
            Large:
              name: Large
              modifiers:
              - public
              - static
              type:
                basic: ChatSettings.FontSize
                full: zombie.chat.ChatSettings$FontSize
            Medium:
              name: Medium
              modifiers:
              - public
              - static
              type:
                basic: ChatSettings.FontSize
                full: zombie.chat.ChatSettings$FontSize
            NotDefine:
              name: NotDefine
              modifiers:
              - public
              - static
              type:
                basic: ChatSettings.FontSize
                full: zombie.chat.ChatSettings$FontSize
            Small:
              name: Small
              modifiers:
              - public
              - static
              type:
                basic: ChatSettings.FontSize
                full: zombie.chat.ChatSettings$FontSize
          constructors:
          - modifiers:
            - private
          staticMethods:
          - name: $values
            modifiers:
            - private
            - static
            return:
              type:
                basic: ChatSettings.FontSize
                full: zombie.chat.ChatSettings$FontSize[]
          - name: valueOf
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: ChatSettings.FontSize
                full: zombie.chat.ChatSettings$FontSize
          - name: values
            modifiers:
            - public
            - static
            return:
              type:
                basic: ChatSettings.FontSize
                full: zombie.chat.ChatSettings$FontSize[]
              notes: an array containing the constants of this enum class, in the
                order they are declared
            notes: 'Returns an array containing the constants of this enum class,
              in

              the order they are declared.'
