version: '1.1'
languages:
  java:
    packages:
      zombie.chat:
        ChatSettings:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            allowBBcode:
              name: allowBBcode
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            allowChatIcons:
              name: allowChatIcons
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            allowColors:
              name: allowColors
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            allowFonts:
              name: allowFonts
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            allowImages:
              name: allowImages
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            bold:
              name: bold
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            equalizeLineHeights:
              name: equalizeLineHeights
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            font:
              name: font
              modifiers:
              - private
              type:
                basic: UIFont
                full: zombie.ui.UIFont
            fontColor:
              name: fontColor
              modifiers:
              - private
              type:
                basic: Color
                full: zombie.core.Color
            fontSize:
              name: fontSize
              modifiers:
              - private
              type:
                basic: ChatSettings.FontSize
                full: zombie.chat.ChatSettings$FontSize
            range:
              name: range
              modifiers:
              - private
              type:
                basic: float
                full: float
            showAuthor:
              name: showAuthor
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            showChatTitle:
              name: showChatTitle
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            showTimestamp:
              name: showTimestamp
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            unique:
              name: unique
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            useOnlyActiveTab:
              name: useOnlyActiveTab
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            zombieAttractionRange:
              name: zombieAttractionRange
              modifiers:
              - private
              type:
                basic: float
                full: float
          staticFields:
            infinityRange:
              name: infinityRange
              modifiers:
              - public
              - static
              type:
                basic: float
                full: float
          constructors:
          - modifiers:
            - public
          - modifiers:
            - public
            parameters:
            - name: bb
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
          methods:
          - name: getFont
            modifiers:
            - public
            return:
              type:
                basic: UIFont
                full: zombie.ui.UIFont
          - name: getFontColor
            modifiers:
            - public
            return:
              type:
                basic: Color
                full: zombie.core.Color
          - name: getFontSize
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getRange
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getZombieAttractionRange
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: isAllowBBcode
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isAllowChatIcons
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isAllowColors
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isAllowFonts
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isAllowImages
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isBold
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isEqualizeLineHeights
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isShowAuthor
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isShowChatTitle
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isShowTimestamp
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isUnique
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isUseOnlyActiveTab
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: pack
            modifiers:
            - public
            parameters:
            - name: bb
              type:
                basic: ByteBufferWriter
                full: zombie.core.network.ByteBufferWriter
            return:
              type:
                basic: void
                full: void
          - name: setAllowBBcode
            modifiers:
            - public
            parameters:
            - name: allowBBcode
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setAllowChatIcons
            modifiers:
            - public
            parameters:
            - name: allowChatIcons
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setAllowColors
            modifiers:
            - public
            parameters:
            - name: allowColors
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setAllowFonts
            modifiers:
            - public
            parameters:
            - name: allowFonts
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setAllowImages
            modifiers:
            - public
            parameters:
            - name: allowImages
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setBold
            modifiers:
            - public
            parameters:
            - name: bold
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setEqualizeLineHeights
            modifiers:
            - public
            parameters:
            - name: equalizeLineHeights
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setFont
            modifiers:
            - public
            parameters:
            - name: font
              type:
                basic: UIFont
                full: zombie.ui.UIFont
            return:
              type:
                basic: void
                full: void
          - name: setFontColor
            modifiers:
            - public
            parameters:
            - name: fontColor
              type:
                basic: Color
                full: zombie.core.Color
            return:
              type:
                basic: void
                full: void
          - name: setFontColor
            modifiers:
            - public
            parameters:
            - name: r
              type:
                basic: float
                full: float
            - name: g
              type:
                basic: float
                full: float
            - name: b
              type:
                basic: float
                full: float
            - name: a
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setFontSize
            modifiers:
            - public
            parameters:
            - name: fontSize
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: setRange
            modifiers:
            - public
            parameters:
            - name: range
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setShowAuthor
            modifiers:
            - public
            parameters:
            - name: showAuthor
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setShowChatTitle
            modifiers:
            - public
            parameters:
            - name: showChatTitle
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setShowTimestamp
            modifiers:
            - public
            parameters:
            - name: showTimestamp
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setUnique
            modifiers:
            - public
            parameters:
            - name: unique
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setUseOnlyActiveTab
            modifiers:
            - public
            parameters:
            - name: useOnlyActiveTab
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setZombieAttractionRange
            modifiers:
            - public
            parameters:
            - name: zombieAttractionRange
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
